### ISSUE TITLE
Possible errors in TCP congestion control

### ISSUE THREAD

**Issue by AdrienDefer** [cnp3/ebook#103]
Hello,

I think there are some errors in TCP Congestion control section. 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/49999026/119628265-3a7c2980-be0d-11eb-9791-0516852bec67.png">

Normally, in the third "if", the cwind should by double, or here the code just add one MSS to it ! I would replace "cwnd = cwnd + MSS" by "cwind = 2 * cwind".

And in the "else" juste under the cwind is supposed the increase by one, so I would replace "cwnd = cwnd + MSS * (MSS / cwnd)" by "cwind = cwind + MSS"

Can you tell me if I am right ?

Adrien

**Comment by qdeconinck** [comment]
Nope, the algorithm is correct. How many ACKs will you receive after one RTT?
