### ISSUE TITLE
Change the figure 19 to match the clearer version on the website

### ISSUE THREAD

**Issue by mshwf** [cnp3/ebook#104]
The figure 19 in section 1.2.1 (The datagram organization/ PDF) uses an image with low resolution that is hard to understand, I found the HTML version is more precise, clearer, and easier to understand:

![](https://beta.computer-networking.info/syllabus/default/_images/tikz-fef8b21a0070744e68d80a30502ff1609660cfeb.png)

https://beta.computer-networking.info/syllabus/default/principles/network.html#the-datagram-organization

**Comment by qdeconinck** [comment]
The PDF version only has punctual builds (the last should have been in February, before a large pass was made on the ebook). We will likely build another PDF when the 3rd edition is finalized. In the meanwhile, you can still generate a PDF using sphinx (the latexpdf build target if I am correct).

**Comment by qdeconinck** [comment]
All the instructions should be in the BUILD.md, but it is for HTML only. If you want to build the PDF, change in the sphinx-build command `-b html` by `-b latexpdf`.

**Comment by mshwf** [comment]
I successfully built the HTML version, but when I try to build the PDF, using this command:
> sphinx-build --keep-going -b latexpdf . builtpdf

I get this error:

> Running Sphinx v4.0.2
> loading translations [en]... done
> Initializing Spelling Checker 7.2.1
> 
> Sphinx error:
> Builder name latexpdf not registered or available through entry point

**Comment by qdeconinck** [comment]
The easiest way to do it seems to run `sphinx-quickstart` at another place, take the Makefile to place it in the root of this repository and then `make latexpdf`.

Also, we had some troubles with recent Sphinx 4 releases, you may want to stay on version 3.5.4.

**Comment by obonaventure** [comment]
You need to use sphinx-build -M latexpdf 
And not sphinx-build -b

**Comment by obonaventure** [comment]
This issue should be fixed by the commit above. The HTML pages have not yet been updated on the webpage, but if you rebuilt it locally it should work.
