### ISSUE TITLE
There might be a typo: west interface not north

### ISSUE THREAD

**Issue by mshwf** [cnp3/ebook#106]
In the [section](https://beta.computer-networking.info/syllabus/default/principles/network.html#computing-forwarding-tables) “Computing forwarding tables”
Shouldn’t 
R1 learns that A is reachable via its North interface.
Be:
R1 learns that A is reachable via its West interface.

since, as per the shown diagram, A lies at the west side of R1?

**Comment by qdeconinck** [comment]
That's correct. Feel free to open a PR to fix this.
