### ISSUE TITLE
erreur de schema ?

### ISSUE THREAD

**Issue by benjilollebg** [cnp3/ebook#107]
le schema numero 3 ou 4, celui ou le recepteur perd un bit du a son horloge ets je pense érroné. En effet l'erreur provient seulement du réceoteur et de son horloge et pas du lien physique donc ne devrait il pas y'avoir le trajet du bit en pointillé jusqu'au recepteur mais ensuite pas de data.ind pour celui-ci ?

Benjamin Demartin

**Comment by qdeconinck** [comment]
Euh what?
Please be much more specific, I don't understand where the issue stands nor what is the issue... And please reread yourself...

**Comment by benjilollebg** [comment]
pour ce schéma ci : https://beta.computer-networking.info/syllabus/default/_images/mscgen-bb7f3c74f2faa89ac35bf3e3b87effddbf6030b6.png

on voit qu'il y a un data.req mais que celui-ci n'est pas recu par le receiver. Il est noté que ceci vient du fait que les horloges ne sont pas synchronizée et le bit n'est donc pas lu. Dans le schéma on a l'impression que l'erreur vient de la couche physique et que celle-ci ne transmet pas le bit. je me demande donc si il ne faut pas mettre les lignes en pointillé comme pour les deux autres data.req

**Comment by qdeconinck** [comment]
I'm not sure this would add value, but if you want to propose something, feel free.

**Comment by qdeconinck** [comment]
In the absence of proposal, this seems not to be an issue anymore.
