### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by benjilollebg** [cnp3/ebook#108]
les erreurs ont été remarquée dans le pdf, et sont donc localisées grace au numéro de page.

page 71 dernier paragraphe : only a few hosts "were" connected.

page 78 premier paragrahe ligne 9 : in a large network"/s"

page 106 avant avant dernier paragraphe "at any time"

Demartin Benjamin

**Comment by qdeconinck** [comment]
The PDF version is quite old compared to the current build. Please check if these typos are still there, and in which section. I think some of them have been fixed before.
