### ISSUE TITLE
Error of rending (protocols/ipv6.html)

### ISSUE THREAD

**Issue by gauone** [cnp3/ebook#19]
One figure is not drawn in [the protocols/IPv6 chapter](http://beta.computer-networking.info/syllabus/default/protocols/ipv6.html).
The figure is located just after the phrase "Both Belnet and the commercial ISP are connected to the global Internet."

**Comment by obonaventure** [comment]
There was a strange problem with sphinx. The problem did not occur in the pdf output, only in the HTML version. In addition, we had a disk crash on our cloud servers today :-(
The problem should be fixed tomorrow with the nightly build.
