### ISSUE TITLE
Distance Vector error in Fig. 27 : "Routing tables computed by distance vector after a failure"

### ISSUE THREAD

**Issue by AdrienDefer** [cnp3/ebook#37]
The distance vector sent from D to A must be [A=1,B=2,C=2,D=0,E=1] and not [A=1,B=2,C=2,D=1,E=1] because the distance from D to D is 0 and not 1.

**Comment by qdeconinck** [comment]
Good catch! Feel free to make a quick PR, we can merge it afterwards

**Comment by AdrienDefer** [comment]
Unfortunately I don't really know how to do it... Can you help me ?

**Comment by qdeconinck** [comment]
I suggest you to read

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

and 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

You can either :

* fork the repository, modify the file to your own repo in a new branch, push the branch and them propose the Pull Request (GitHub will propose you to do so)
* browse the file of interest on the host repo on Github (in your case it is principles/dv.rst), and near the Raw and Blame buttons at the top right of the file content you have an edit button (a pencil) that will allow you to make the modification on the Web page and submit the PR. Note that you need to modify both the tikz image AND the text associated (the error is present at the two spots).

I can also make the commit, but in that case you would lose the credits of finding and solving the issue (would be a pity). Furthermore, this makes a good git exercise :)

**Comment by AdrienDefer** [comment]
Normally it should be done (I've just edit and publish my branch), I've edit one another mistake in the makefile : "gituhb" in place of "github". Can you confirm ?
