### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by chaddcw** [cnp3/ebook#47]
I had to add the following modules to requirements.txt to build the book:

```
sphinxcontrib-mscgen
sphinxcontrib-tikz
```

I'm not sure if this is a mis-configuration on my part or missing from the documentation.  This is using Python 3.7.3.

**Comment by qdeconinck** [comment]
Indeed, this seems missing in the BUILD.md file. Note that we rely on patched version of these modules to have proper HTML and PDF builds. You can have a look at the `travis.sh` file having the following lines:
```bash
git clone https://github.com/obonaventure/mscgen.git
pip3 install -e mscgen
git clone https://github.com/obonaventure/tikz.git
pip3 install -U -e tikz
```
Feel free to make a PR fixing this, otherwise I can fix this in the coming weeks.
