### ISSUE TITLE
Non draft edition 

### ISSUE THREAD

**Issue by mshwf** [cnp3/ebook#62]
Thanks for the efforts.
I want to start reading this book, I'd like to pick up the latest non-draft edition. But the third is still draft, and also the second edition, there's a draft label on it.
Is it still in writing, what edition do you recommend? 
I'm a software developer willing to understand the basics of networking, no deep knowledge required. 
Thanks.

**Comment by qdeconinck** [comment]
This book is said to be in "draft edition", but actually it is readable as it (this book serves as the main one for the networking course in our university given this semester). Only small fixes remain to be done, and we will likely place the "3rd edition" release in the coming weeks. So you can read the https://beta.computer-networking.info/ version without too much troubles (and if there are, don't hesitate to place an issue here :) ).

**Comment by mshwf** [comment]
Thank you for your response. In the next release, will the ebook be available in epub and pdf formats?

**Comment by qdeconinck** [comment]
Actually, they should be there but we manually generate them so far to avoid having exercises in these versions, so they might be missing now. In the meantime, you can still generate these versions by yourself or by using the latest publicly available release (https://github.com/cnp3/ebook/releases/tag/beta3-dec10) that is also readable, but that does not contain the fixes/rewritings from this year.

**Comment by mshwf** [comment]
I actually downloaded and reading the epub and pdf files from https://www.computer-networking.info/secondedition.html
but it says:
"The second edition of the ebook is currently being written. "
which is confusing as the third edition is about to be released.

**Comment by qdeconinck** [comment]
Indeed, I think this mention has been kept to let users provide issues/PRs to this edition, however we are not maintaining it anymore. I filled https://github.com/obonaventure/cnp3/issues/271 to address this.

**Comment by obonaventure** [comment]
I have updated the third edition to remove the draft sentences. A new build is available from https://www.computer-networking.info and I've started to add GitHub actions to create the pdf and epub files automatically on GitHub.
