### ISSUE TITLE
A typo in datalink chapter

### ISSUE THREAD

**Issue by mshwf** [cnp3/ebook#74]
There's a little typo in:
"A frame can be defined has a sequence of bits that has a particular syntax or structure"
should be 
"A frame can be defined as a sequence of bits that has a particular syntax or structure"

has> as

In the future, can I  edit just this file?:
https://github.com/cnp3/ebook/blob/eeb5e7ba9d4b3ea66c707ec6c4a25fb1302a34da/locale/pot/principles/reliability.pot

**Comment by qdeconinck** [comment]
Thanks for spotting this. I would prefer directly editing the source md themselves, as pot files are generated based on them (so your correction would disappear at some point).
