### ISSUE TITLE
SSH - key exchange error 

### ISSUE THREAD

**Issue by RobinTilman** [cnp3/ebook#77]
On page 162 in chapter 2.7.1:

"The server generates the random number b. It computes B = g^b mod p, K = B^a mod p ...." should be replaced by "The server generates the random number b. It computes B = g^b mod p, K = A^b mod p". 

Similarly, "The client can recompute K = B^a mod p ...." should be replaced by "The client can recompute K = A^b mod p ...."

**Comment by qdeconinck** [comment]
This seems to have been fixed a while ago.
