### ISSUE TITLE
Error in the picture of "TCP FSM for connection establishment"

### ISSUE THREAD

**Issue by Bendron** [cnp3/ebook#78]
In the The Transmission Control Protocol section, 

![image](https://user-images.githubusercontent.com/56221831/118486749-420b4680-b71a-11eb-9beb-b9d90b4f8ff7.png)

There is a link missing between SYN RCVD and Established, it corresponds to the case when both the client and the server send a SYN segment to open a TCP connection. I posted a screenshot of what it should look like.

**Comment by qdeconinck** [comment]
Nope. If both client and server send a SYN segment, this corresponds to the transition SYN Sent -> SYN Rcvd.

**Comment by Bendron** [comment]
Sorry I think I wasn't precise enough.
I mean the step after SYN Sent -> SYN Rcvd, they will both send a SYN + ACK. And in the FSM, it's not shown that, if they received SYN + ACK while being in the SYN Rcvd state, they will go to Established

**Comment by Bendron** [comment]
I found this error thanks to this text, which is located just next to the FSM
![image](https://user-images.githubusercontent.com/56221831/118507325-6a9d3b80-b72e-11eb-9181-045aff000c6d.png)
