### ISSUE TITLE
Erreur non corrigée dans l'introduction (fibre optique)

### ISSUE THREAD

**Issue by RosarNicolas** [cnp3/ebook#9]
Une erreur concernant les fibre optique dans l'introduction n'a pas été corrigée dans la version numérique du cours "Computer Network".

Il est spécifié qu'un fibre optique multi-mode est utilisée pour un transfert de données longue distance et que la fibre optique mono-mode est utilisée pour de courtes distances (et non l'inverse comme cela devrait être).

![image](https://user-images.githubusercontent.com/32072799/65800888-f89e6a00-e177-11e9-8e26-5130c4a75ba0.png)

**Comment by obonaventure** [comment]
Thanks for spotting this error. I encourage you to submit a pull request, see https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github for a description on how to create pull requests for large projects.
For this error, you can simply fork the repository on github, edit the file directly on github and submit the pull request that I will accept and merge
