### ISSUE TITLE
Graphic error in a figure in section congestion control

### ISSUE THREAD

**Issue by Bendron** [cnp3/ebook#93]
https://beta.computer-networking.info/syllabus/default/principles/sharing.html#congestion-control-with-a-window-based-transport-protocol

There is a graphic error on the figure :
![image](https://user-images.githubusercontent.com/56221831/118689906-cbe50d80-b807-11eb-987a-5a4c041ec6bc.png)

The "S3" is not in is rectangle but it is above.

**Comment by qdeconinck** [comment]
Feel free to make a PR to fix this.
