### ISSUE TITLE
Figure not showing in the section "The application Layer"

### ISSUE THREAD

**Issue by Bendron** [cnp3/ebook#94]
https://beta.computer-networking.info/syllabus/default/protocols/transport-service.html

Both of the figures in this section are broken

The figures are : 
-The connectionless or datagram service
-The connection-oriented or byte-stream service

![image](https://user-images.githubusercontent.com/56221831/118707726-28055d00-b81b-11eb-88ed-84e976e23527.png)

![image](https://user-images.githubusercontent.com/56221831/118707689-1d4ac800-b81b-11eb-8eac-c9483de7d374.png)

**Comment by qdeconinck** [comment]
PR #105 seems to have fixed this.
