### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CLouis-EPL** [cnp3/ebook#95]
Section 2.5 ; page 152 ; two last paragraphes

1) Two directions ... the delivery of THESE WEB PAGES should replace of web these pages.
2) Another possibility ... TO SEND MULTIPLE ... should replace to send the send multiple ... 

Section 2.6 ; page 157 ; Note : second sentence : 
it must be able to DETERMINE should replace determiner

**Comment by qdeconinck** [comment]
The second element was already fixed, but not the first. Feel free to make a PR.

**Comment by CLouis-EPL** [comment]
Done :)

**Comment by qdeconinck** [comment]
Please link the commits of your PR to this issue. Feel free to force push your commit to do so.

**Comment by CLouis-EPL** [comment]
https://github.com/cnp3/ebook/pull/98#issue-649791645 ?

**Comment by qdeconinck** [comment]
This is the PR (and its commits) that needs to reference the issue, not the reverse.
