### ISSUE TITLE
Better Algorithm for LSP

### ISSUE THREAD

**Issue by AdrienDefer** [cnp3/ebook#99]
Hello, 

In the algorithm used to check if the arrival LSP needs to replace the older one in the LSDP. 

I would replace the LSBD.add(LSP) by LSBD.replace(LSP.router, LST) whit a comment saying "replacing the older LSP of LSP.router by the newest". I think it's more accurate ! 

Can you tell me if it is Ok ?

**Comment by qdeconinck** [comment]
The algorithm already states that `LSDB.add(LSP)  # implicitly removes older LSP from same router`. Also, the `add` covers the case where no LSP was previously received from the router.
